---
name: Adam Stacoviak
email: adam@stacoviak.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Adam Stacoviak about life, culture, hacking, podcasting, open source, technology, and whatever else he's curious about.
url: https://adamstacoviak.com
twitter_username: adamstac
github_username:  adamstac

# Build settings
permalink: /:title

# Markdown Rendering
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
markdown_ext:  markdown,mkdown,mkdn,mkd,md,mdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-assets

# Build Info
assets:
  js_compressor: uglifier
  css_compressor: sass
  compress:
    css: false
  sources:
    # - _assets/fonts
    # - _assets/javascripts
    - _assets/images
    - _assets/stylesheets
post:
  extension: md

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string means all files in the project
      type: "pages"
    values:
      layout: "page"

# Build exclusions
exclude:
  - node_modules
  - sass
  - CNAME
  - config.rb
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - Rakefile
  - README.md

# Build inclusions
include:
  - _redirects