# Where things are
source : .
destination : ./_site/
layouts_dir : _layouts
# collections_dir : .
# plugins_dir : _plugins # takes an array of strings and loads plugins in that order
# data_dir : _data
# includes_dir : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output : true
post:
  extension: md

name: Adam Stacoviak
email: adam@stacoviak.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Adam Stacoviak about life, culture, hacking, podcasting, open source, technology, and whatever else he's curious about.
url: https://adamstacoviak.com
twitter_username: adamstac
github_username:  adamstac

# Build settings
permalink: /:title/

# Markdown Rendering
markdown: kramdown
highlighter: rouge
markdown_ext: md
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-assets

# jekyll-feed
feed:
  path: /feed.xml

# jekyll-assets
assets:
  css_compressor: scss
  sources:
    - _sass/stylesheets

# Default teamplates
defaults:
  -
    scope:
      path: "" # an empty string means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string means all files in the project
      type: "pages"
    values:
      layout: "page"

# Build exclusions
exclude:
  - node_modules
  - sass
  - CNAME
  - config.rb
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - Rakefile
  - README.md
  - fly
  - Dockerfile
  - docker-compose.yml

# jekyll-compose
jekyll_compose:
  default_front_matter:
    drafts:
      title:
      slug:
      date:
      type: post
      description:
    posts:
      title:
      slug:
      date:
      type: post
      description:
      category:
      tags:
      published: false
      sitemap: false