# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Adam Stacoviak
email: adam@stacoviak.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
paginate: 10
url: "http://adamstacoviak.com"
feed: "http://adamstacoviak.com/feed.xml"
twitter_username: adamstac
github_username:  adamstac

# Build settings
permalink: /:title

# Markdown Rendering
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
markdown_ext:  markdown,mkdown,mkdn,mkd,md,mdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-assets

# Build Info
assets:
  js_compressor: uglifier
  css_compressor: sass
  compress:
    css: false
  sources:
    # - _assets/fonts
    # - _assets/javascripts
    - _assets/images
    - _assets/stylesheets
post:
  extension: md

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string means all files in the project
      type: "pages"
    values:
      layout: "page"

# Build exclusions
exclude:
  - _drafts
  - node_modules
  - sass
  - CNAME
  - config.rb
  - Gemfile
  - gulpfile.js
  - package.json
  - Rakefile
  - README.md
